"""create table trip

Revision ID: fb3c135e9176
Revises: 
Create Date: 2025-07-02 14:40:03.259935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3c135e9176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('per_trip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trips', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('avg_trip_time', sa.Float(), nullable=True),
    sa.Column('fuel_spent', sa.Float(), nullable=True),
    sa.Column('fuel_litres', sa.Float(), nullable=True),
    sa.Column('total_kilometers', sa.Float(), nullable=True),
    sa.Column('fuel_station', sa.String(length=50), nullable=True),
    sa.Column('vehicle_condition', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('monthly_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_per_day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('best_day', sa.Date(), nullable=True),
    sa.Column('max_trips', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='unique_month_year')
    )
    op.create_table('cost_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('centre_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['cost_centres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', 'centre_id', name='unique_cost_summary')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_summary')
    op.drop_table('monthly_summaries')
    op.drop_table('daily_logs')
    op.drop_table('cost_centres')
    # ### end Alembic commands ###
